// <auto-generated />
using System;
using LuisAngel_GabrieMorillo_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuisAngel_GabrieMorillo_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250715102804_InicialConProductos")]
    partial class InicialConProductos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuisAngel_GabrieMorillo_AP1_P2.Models.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaId"));

                    b.Property<decimal>("CantidadProducida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProducido")
                        .HasColumnType("int");

                    b.Property<double>("PesoTotal")
                        .HasColumnType("float");

                    b.Property<int?>("ProducidoProductoId")
                        .HasColumnType("int");

                    b.HasKey("EntradaId");

                    b.HasIndex("ProducidoProductoId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("LuisAngel_GabrieMorillo_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int>("EntradaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("LuisAngel_GabrieMorillo_AP1_P2.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("bit");

                    b.Property<double>("Existencia")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Maní",
                            EsCompuesto = false,
                            Existencia = 100.0,
                            Peso = 0.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Pistachos",
                            EsCompuesto = false,
                            Existencia = 100.0,
                            Peso = 0.0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Almendras",
                            EsCompuesto = false,
                            Existencia = 100.0,
                            Peso = 0.0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripcion = "Frutos Mixtos 200gr",
                            EsCompuesto = true,
                            Existencia = 0.0,
                            Peso = 200.0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripcion = "Frutos Mixtos 400gr",
                            EsCompuesto = true,
                            Existencia = 0.0,
                            Peso = 400.0
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripcion = "Frutos Mixtos 600gr",
                            EsCompuesto = true,
                            Existencia = 0.0,
                            Peso = 600.0
                        });
                });

            modelBuilder.Entity("LuisAngel_GabrieMorillo_AP1_P2.Models.Entradas", b =>
                {
                    b.HasOne("LuisAngel_GabrieMorillo_AP1_P2.Models.Productos", "Producido")
                        .WithMany()
                        .HasForeignKey("ProducidoProductoId");

                    b.Navigation("Producido");
                });

            modelBuilder.Entity("LuisAngel_GabrieMorillo_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.HasOne("LuisAngel_GabrieMorillo_AP1_P2.Models.Entradas", "Entrada")
                        .WithMany("Detalles")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuisAngel_GabrieMorillo_AP1_P2.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("LuisAngel_GabrieMorillo_AP1_P2.Models.Entradas", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
